
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int LONG_TYPE = 11;
  public static final int SC = 7;
  public static final int INT_TYPE = 8;
  public static final int DOUBLE_TYPE = 9;
  public static final int CM = 5;
  public static final int S = 4;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int POINTER = 13;
  public static final int SO = 6;
  public static final int error = 1;
  public static final int FLOAT_TYPE = 12;
  public static final int CHAR_TYPE = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "ID",
  "S",
  "CM",
  "SO",
  "SC",
  "INT_TYPE",
  "DOUBLE_TYPE",
  "CHAR_TYPE",
  "LONG_TYPE",
  "FLOAT_TYPE",
  "POINTER"
  };
}

